In [1]:
import numpy as np

In [2]:
np.__version__

'2.0.2'

In [3]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [12]:
arr1 = np.array([1,3,5,7,9])
type(arr1)

numpy.ndarray

In [13]:
arr2 = np.array([1,3,5,7,9])
type(arr2)

numpy.ndarray

In [19]:
id(arr1)

132442223383472

In [15]:
id(arr2)

132442223390192

In [20]:
arr3 = arr1
print(id(arr1), id(arr3))

132442223383472 132442223383472


In [21]:
arr4 = np.copy(arr1)
print(arr4)
print(id(arr4), id(arr1))

[1 3 5 7 9]
132442222911120 132442223383472


In [22]:
type((1,2,3,4,5))

tuple

In [23]:
np.array((1,2,3,4,5))

array([1, 2, 3, 4, 5])

In [24]:
arr6 = np.array((1,2,3,4,5))
type(arr6)

numpy.ndarray

In [25]:
type({'one':1, 'two':2, 'three':3})

dict

In [28]:
arr7 = np.array({'one':1, 'two':2, 'three':3})
print(arr7)
type(arr7)

{'one': 1, 'two': 2, 'three': 3}


numpy.ndarray

In [29]:
{1,2,3}

{1, 2, 3}

In [30]:
type({1,2,3})

set

In [61]:
arr8 = np.array({1,2,3})
print(arr8)
type(arr8)

{1, 2, 3}


numpy.ndarray

In [33]:
[i for i in range(10)]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [34]:
[i for i in np.arange(10)]

[np.int64(0),
 np.int64(1),
 np.int64(2),
 np.int64(3),
 np.int64(4),
 np.int64(5),
 np.int64(6),
 np.int64(7),
 np.int64(8),
 np.int64(9)]

In [35]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [43]:
lens = np.arange(10)
len(lens)

10

In [44]:
lens.size

10

In [52]:
arr9 = np.array([111,2.3,True])
type(arr9[0])

numpy.float64

In [59]:
arr10 = np.array([111,True,'hi'])
type(arr10[0])

numpy.str_

In [81]:
arr11 = np.array([13,12,True])
type(arr11[2])

numpy.int64

In [82]:
np.array(['apple','banana','strawberry'])

array(['apple', 'banana', 'strawberry'], dtype='<U10')

In [83]:
arr12 = np.array(['apple','banana','strawberry'])
type(arr12[0])

numpy.str_

In [86]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [90]:
np.linspace(-10,10,20)

array([-10.        ,  -8.94736842,  -7.89473684,  -6.84210526,
        -5.78947368,  -4.73684211,  -3.68421053,  -2.63157895,
        -1.57894737,  -0.52631579,   0.52631579,   1.57894737,
         2.63157895,   3.68421053,   4.73684211,   5.78947368,
         6.84210526,   7.89473684,   8.94736842,  10.        ])

In [91]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [94]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [102]:
li1 = [[1,2,3],[4,5,6],[7,8,9]]
li1[0][0]

1

In [98]:
np.array(li1)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [107]:
arr2d = np.array(li1)
arr2d.ndim

2

In [106]:
arr1d = np.array([1,3,5,7,9])
arr2.ndim

1

In [110]:
np.array([[[1,2],[4,5],[6,7]],[[8,9],[10,11],[4,5]]])

array([[[ 1,  2],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [ 4,  5]]])

In [112]:
arr3d = np.array([[[1,2],[3,4]], [[5,6],[7,8]]])
arr3d.ndim

3

In [115]:
arr3d[0][1][0]

np.int64(3)

In [116]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [120]:
arr2dZero1 = np.zeros((2,3))
type(arr2dZero1[0][0])

numpy.float64

In [125]:
arr2dZero2 = np.zeros((2,3), dtype='int32')
arr2dZero2

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [126]:
type(arr2dZero2[0][0])

numpy.int32

In [127]:
arr2dZero2.astype('float32')

array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)

In [128]:
arr2dZero2

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [135]:
arr2dZero2 = arr2dZero2.astype('float32')

In [136]:
arr2dZero2

array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)

In [141]:
# size, shape and ndim is an property not a method
a = np.array([[1,2,3,5],[4,5,6,3],[7,8,9,1]])

In [142]:
a.size

12

In [143]:
a.shape

(3, 4)

In [144]:
a.ndim

2

In [145]:
a1 = np.array([2,5,1,3])

In [149]:
a1.size

4

In [150]:
a1.shape # no of elements

(4,)

In [151]:
a1.ndim

1

In [154]:
a2 = np.arange(15)
a2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [156]:
a2.reshape((3,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [157]:
a2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [158]:
a2 = a2.reshape((3,5))

In [159]:
a2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [160]:
a3 = np.arange(15)
a3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [161]:
a3 = a3.reshape((5,3))
a3

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [176]:
data = np.random.randn(2,3)
data

array([[ 1.06502004,  0.46049678, -0.16726451],
       [ 0.34920792, -1.01872593,  0.49722679]])

In [177]:
np.mean(data)

np.float64(0.19766018288797524)

In [178]:
np.std(data)

np.float64(0.6515197963507267)

In [179]:
data2 = np.random.randn(100,100)
data2

array([[-0.80540586,  0.28560566, -0.76482948, ...,  0.75219087,
         0.37099308, -0.58814808],
       [ 2.73754409,  0.31588506,  0.46944214, ...,  0.17924791,
         1.34520959,  0.28513339],
       [-0.8607643 ,  1.19944188, -0.33518741, ...,  1.53203667,
        -0.48357393,  0.85614653],
       ...,
       [-0.80403019, -0.49166378,  1.42863545, ..., -0.19402914,
         0.34841629,  1.6838349 ],
       [-1.04122034, -0.17192229,  0.21614261, ...,  1.15168627,
        -0.12015053,  0.95173663],
       [ 0.2028212 ,  0.39543151,  0.3284039 , ..., -2.19544327,
        -0.38256383, -0.39159455]])

In [180]:
np.mean(data2)

np.float64(-0.0017243967753258844)

In [181]:
np.std(data2)

np.float64(0.9961146946179572)

In [182]:
data3 = np.random.randn(1000,1000)
data3

array([[-0.62827132,  0.92045033, -2.19302312, ...,  1.25004606,
         0.01216384, -0.05232796],
       [-0.54543863,  0.10050063, -1.61182423, ..., -0.22847144,
        -0.21882785,  0.86968224],
       [-1.34604867, -0.30710047, -0.63700028, ...,  1.67319185,
        -0.20320682, -2.21779501],
       ...,
       [-3.30622119, -1.93064433,  0.21791692, ...,  0.39929901,
        -0.23294877,  0.462691  ],
       [-1.83523344, -0.76429192,  1.17505725, ...,  2.72954602,
        -0.54001048,  0.17887548],
       [-1.29711349, -0.80066809, -0.64759865, ..., -1.03762437,
        -0.69654772, -0.04030884]])

In [183]:
np.mean(data3)

np.float64(0.0008656311156621061)

In [184]:
np.std(data3)

np.float64(0.9998506477550956)

In [185]:
np.arange(1000000)

array([     0,      1,      2, ..., 999997, 999998, 999999])

In [187]:
type(np.arange(1000000))

numpy.ndarray

In [186]:
list(range(1000000))

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,


In [193]:
%time for i in range(1000): np.arange(1000000) * 2

CPU times: user 1.76 s, sys: 1.52 ms, total: 1.76 s
Wall time: 1.8 s


In [194]:
%time for i in range(1000): list(range(1000000)) * 2

CPU times: user 36.4 s, sys: 10.3 s, total: 46.8 s
Wall time: 47 s


In [196]:
a = np.array([1,2,3])
b = np.append(a, [4,5,6])
b

array([1, 2, 3, 4, 5, 6])

In [197]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [203]:
b = np.append(a,[[9,5]], axis=0) # Row - Vertical
b

array([[1, 2],
       [3, 4],
       [9, 5]])

In [205]:
c = np.append(b,[[6],[7],[8]], axis=1) # Column - Horizontal
c

array([[1, 2, 6],
       [3, 4, 7],
       [9, 5, 8]])

In [206]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [207]:
np.delete(a,3)

array([1, 2, 3, 5, 6])

In [208]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [209]:
np.delete(a,0,axis=0)

array([[4, 5, 6]])

In [210]:
np.delete(a,1,axis=1)

array([[1, 3],
       [4, 6]])