Comparing Python Lists and NumPy Arrays: + Operator

In [ ]:
import numpy as np

In [ ]:
# List
a = [1,2,3]
b = [4,5,6]
a + b

[1, 2, 3, 4, 5, 6]

In [ ]:
# Numpy Arrays
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr1 + arr2

array([5, 7, 9])

If the shape of array is the same, addition, subtraction, multiplication, and division operations can be performed

In [ ]:
print(arr1.ndim)
print(arr1.size)
print(arr1.shape)

1
3
(3,)


In [ ]:
print(arr2.ndim)
print(arr2.size)
print(arr2.shape)

1
3
(3,)


In [ ]:
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)

[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


Comparing Python Lists and NumPy Arrays : Multiplication

In [ ]:
a = [1,2,3]
a * 3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [ ]:
b = np.array([1,2,3])
b * 3

array([3, 6, 9])

repeat and tile

In [ ]:
b

array([1, 2, 3])

In [ ]:
np.repeat(b,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [ ]:
np.tile(b,3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

When using tile method, the array can be repeated into a two dimensional form.

In [ ]:
c = np.arange(9)
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
c = c.reshape(3,3)
c

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
c.shape

(3, 3)

In [ ]:
np.tile(c,3)

array([[0, 1, 2, 0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8, 6, 7, 8]])

In [ ]:
np.repeat(c,3)

array([0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, 6, 6, 7,
       7, 7, 8, 8, 8])

Exponential Operations

In [ ]:
arr2

array([4, 5, 6])

In [ ]:
arr2**2

array([16, 25, 36])

In [ ]:
arr1 / (arr2**2)

array([0.0625    , 0.08      , 0.08333333])

Comparision operations

In [ ]:
arr3 = np.array([10,20,30,40,50])
arr3

array([10, 20, 30, 40, 50])

In [ ]:
arr3 > 10

array([False,  True,  True,  True,  True])

Universal functions

In [ ]:
x = np.array([0,1,2,3])
x

array([0, 1, 2, 3])

In [ ]:
x**3

array([ 0,  1,  8, 27])

In [ ]:
np.sqrt(x)

array([0.        , 1.        , 1.41421356, 1.73205081])

Statistical methods od NumPy arrays

In [ ]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
x = np.arange(1,11)

In [ ]:
x.sum()

np.int64(55)

In [ ]:
x.mean()

np.float64(5.5)

In [ ]:
x_mean = x.mean()

In [ ]:
x - x_mean

array([-4.5, -3.5, -2.5, -1.5, -0.5,  0.5,  1.5,  2.5,  3.5,  4.5])

In [ ]:
(x - x_mean)**2

array([20.25, 12.25,  6.25,  2.25,  0.25,  0.25,  2.25,  6.25, 12.25,
       20.25])

In [ ]:
dev = (x-x_mean)**2
dev.sum()

np.float64(82.5)

In [ ]:
dev.sum() / x.size

np.float64(8.25)

In [ ]:
x.var()

np.float64(8.25)

In [ ]:
np.sqrt(x.var())

np.float64(2.8722813232690143)

In [ ]:
x.cumsum()

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55])

In [ ]:
x = np.arange(1,7)
x

array([1, 2, 3, 4, 5, 6])

In [ ]:
x.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
x.reshape(2,-1)

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
x.reshape(-1,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
x = x.reshape(2,3)
x

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
x.mean(axis=0)

array([2.5, 3.5, 4.5])

In [ ]:
x.mean(axis=1)

array([2., 5.])

In [ ]:
np.random.seed(123)

In [ ]:
np.random.randint(10)

2

In [ ]:
np.random.randint(1,11)

3

In [ ]:
while True:
  num = np.random.randint(1,11)
  print(num)
  if num == 1:
    break

9
8
8
5
5
6
1


In [ ]:
x = np.array([0,1,2,3,4,5])
x

array([0, 1, 2, 3, 4, 5])

In [ ]:
np.sqrt(x)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798])

In [ ]:
np.exp(x)

array([  1.        ,   2.71828183,   7.3890561 ,  20.08553692,
        54.59815003, 148.4131591 ])

In [ ]:
np.random.seed(123)
a = np.random.randint(1, 11, size=100)
a

array([ 3,  3,  7,  2,  4, 10,  7,  2,  1,  2, 10,  1,  1, 10,  4,  5,  1,
        1,  5,  2,  8,  4,  3,  5,  8,  3,  5,  9,  1,  8, 10,  4,  5,  7,
        2,  6,  7,  3,  2,  9,  4,  6,  1,  3,  7,  3,  5,  5,  7,  4,  1,
        7,  5,  8,  7,  8,  2,  6,  8, 10,  3,  5,  9,  2,  3,  2,  2,  4,
        6, 10,  1,  9,  2,  7,  4,  4,  6, 10,  8, 10,  3,  4,  4,  4,  9,
        7, 10,  8,  7,  4, 10,  7,  7,  7,  2,  4,  5,  4,  2,  1])

In [ ]:
a.size

100

In [ ]:
np.unique(a)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.median(a)

np.float64(5.0)

In [ ]:
np.sum(a)

np.int64(513)

In [ ]:
np.round(np.var(a),2)

np.float64(7.93)

In [ ]:
z = np.arange(10)

In [ ]:
np.mean(z)

np.float64(4.5)

In [ ]:
z.mean()

np.float64(4.5)

In [ ]:
(z - z.mean())

array([-4.5, -3.5, -2.5, -1.5, -0.5,  0.5,  1.5,  2.5,  3.5,  4.5])

In [ ]:
np.sqrt(sum((z - z.mean())**2) // z.size)

np.float64(2.8284271247461903)

In [ ]:
sum(abs(z - z.mean())) // z.size

np.float64(2.0)

In [ ]:
np.round(np.var(a),2)

np.float64(7.93)

In [ ]:
np.round(np.mean(a),2)

np.float64(5.13)

In [ ]:
np.round(np.std(a),2)

np.float64(2.82)

In [ ]:
np.max(a)

np.int64(10)

In [ ]:
np.min(a)

np.int64(1)

In [ ]:
z = np.random.randint(10,size=100)

In [ ]:
np.unique(z)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
set(z)

{np.int64(0),
 np.int64(1),
 np.int64(2),
 np.int64(3),
 np.int64(4),
 np.int64(5),
 np.int64(6),
 np.int64(7),
 np.int64(8),
 np.int64(9)}

In [ ]:
a = np.array([2,-3,4,5,7,0,1,-1])

In [ ]:
a.argmax()

np.int64(4)

In [ ]:
a.argmin()

np.int64(1)

Matrix Operations


In [ ]:
A = np.array([0,1,2,3]).reshape(2,2)
A

array([[0, 1],
       [2, 3]])

In [ ]:
B = np.array([3,2,0,1]).reshape(2,2)
B

array([[3, 2],
       [0, 1]])

In [ ]:
A.dot(B)

array([[0, 1],
       [6, 7]])

In [ ]:
np.dot(A,B)

array([[0, 1],
       [6, 7]])

In [ ]:
np.transpose(A)

array([[0, 2],
       [1, 3]])

In [ ]:
A.transpose()

array([[0, 2],
       [1, 3]])

In [ ]:
np.linalg.inv(A)

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [ ]:
np.linalg.det(A)

np.float64(-2.0)

NumPy Indexing and Slicing

In [ ]:
a = np.array([0,1,2,3])
b = np.array([[0,1,2,3],
              [4,5,6,7],
              [8,9,10,11]])

In [ ]:
a[0]

np.int64(0)

In [ ]:
b[0]

array([0, 1, 2, 3])

In [ ]:
b[0][1]

np.int64(1)

In [ ]:
b[0,1]

np.int64(1)

In [ ]:
a1 = np.array([0,10,20,30,40,50])
a1[5]

np.int64(50)

In [ ]:
a1[5] = 70

In [ ]:
a1

array([ 0, 10, 20, 30, 40, 70])

to access multiple elements

In [ ]:
a1[[1,3,4]]

array([10, 30, 40])

In [ ]:
a2 = np.arange(10,100,5).reshape(3,6)
a2

array([[10, 15, 20, 25, 30, 35],
       [40, 45, 50, 55, 60, 65],
       [70, 75, 80, 85, 90, 95]])

In [ ]:
a2[0,2]

np.int64(20)

In [ ]:
a2[2,5] = 100
a2

array([[ 10,  15,  20,  25,  30,  35],
       [ 40,  45,  50,  55,  60,  65],
       [ 70,  75,  80,  85,  90, 100]])

In [ ]:
a2[1]

array([40, 45, 50, 55, 60, 65])

In [ ]:
a2[2] = np.array([1,2,3,4,5,6])
a2

array([[10, 15, 20, 25, 30, 35],
       [40, 45, 50, 55, 60, 65],
       [ 1,  2,  3,  4,  5,  6]])

In [ ]:
a2[[0,2],[0,1]] # (0,0) (2,1)

array([10,  2])

In [ ]:
a = np.array([1,2,3,4,5,6])
a[a>3]

array([4, 5, 6])

In [ ]:
a[a%2==0]

array([2, 4, 6])

In [ ]:
b1 = np.arange(0,60,10)
b1

array([ 0, 10, 20, 30, 40, 50])

In [ ]:
b1[1:4]

array([10, 20, 30])

In [ ]:
b1[:3]

array([ 0, 10, 20])

In [ ]:
b1[2:]

array([20, 30, 40, 50])

In [ ]:
arr2d = np.arange(1,10).reshape(3,3)
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [ ]:
arr2d[1,:2]

array([4, 5])

In [ ]:
arr2d[:2,2]

array([3, 6])

In [ ]:
arr2d[:,:1]

array([[1],
       [4],
       [7]])

In [ ]:
names = np.array(['Bob','Joe','Tom','Bob','Tom','Joe','Joe'])

In [ ]:
names

array(['Bob', 'Joe', 'Tom', 'Bob', 'Tom', 'Joe', 'Joe'], dtype='<U3')

In [ ]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [ ]:
names[names == 'Bob']

array(['Bob', 'Bob'], dtype='<U3')

In [ ]:
np.empty((8,4))

array([[1.  , 0.  , 0.16, 1.  ],
       [1.  , 0.  , 0.  , 1.  ],
       [1.  , 1.  , 0.  , 1.  ],
       [0.  , 1.  , 0.  , 1.  ],
       [0.  , 1.  , 1.  , 1.  ],
       [0.  , 0.  , 1.  , 1.  ],
       [1.  , 0.  , 1.  , 1.  ],
       [1.  , 0.  , 0.75, 1.  ]])

In [ ]:
arr = np.empty((8,4))
arr

array([[1.  , 0.  , 0.16, 1.  ],
       [1.  , 0.  , 0.  , 1.  ],
       [1.  , 1.  , 0.  , 1.  ],
       [0.  , 1.  , 0.  , 1.  ],
       [0.  , 1.  , 1.  , 1.  ],
       [0.  , 0.  , 1.  , 1.  ],
       [1.  , 0.  , 1.  , 1.  ],
       [1.  , 0.  , 0.75, 1.  ]])

In [ ]:
for i in range(8):
  arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [ ]:
arr[[4,3,0,6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [ ]:
arr[[-3,-5]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.]])

In [ ]:
arr2 = np.arange(20)
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
arrMask = (arr2 % 5 == 0)

In [ ]:
arr2[arrMask]

array([ 0,  5, 10, 15])

In [ ]:
arr2>10

array([False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [ ]:
arrMask2 = (arr2>=10)

In [ ]:
arr2[arrMask & arrMask2]

array([10, 15])

Array Transposition

In [ ]:
arr = np.arange(15).reshape((3,5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
arr.transpose()

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [ ]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [ ]:
arr = np.random.randn(6,3)
arr

array([[-0.82343141,  0.13021495,  1.26729865],
       [ 0.33276498,  0.5565487 , -0.21208012],
       [ 0.4562709 ,  1.54454445, -0.23966878],
       [ 0.14330773,  0.25381648,  0.28372536],
       [-1.41188888, -1.87686866, -1.01965507],
       [ 0.1679423 ,  0.55385617, -0.53067456]])

In [ ]:
arr.T

array([[-0.82343141,  0.33276498,  0.4562709 ,  0.14330773, -1.41188888,
         0.1679423 ],
       [ 0.13021495,  0.5565487 ,  1.54454445,  0.25381648, -1.87686866,
         0.55385617],
       [ 1.26729865, -0.21208012, -0.23966878,  0.28372536, -1.01965507,
        -0.53067456]])

In [ ]:
np.dot(arr.T,arr)

array([[3.03912686, 3.56202723, 0.16771675],
       [3.56202723, 6.60613537, 1.36866467],
       [0.16771675, 1.36866467, 3.11027699]])

In [ ]:
arr_1 = np.arange(12).reshape(3,4)
arr_1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
arr_1.reshape((4,3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
arr_1.transpose((0,1))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
arr_1.transpose((1,0))

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [ ]:
arr = np.arange(16).reshape((2,2,4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [ ]:
arr.transpose((1,0,2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [ ]:
arr.transpose((0,1,2))

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [ ]:
arr.transpose((2,1,0))

array([[[ 0,  8],
        [ 4, 12]],

       [[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]]])

In [ ]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [ ]:
arr.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

In [ ]:
arr.swapaxes(0,1)

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])