How to create a *series*

In [ ]:
import pandas as pd

In [ ]:
pd.Series(['Male','Female','Male','Male','Female','Female','Female'])

0      Male
1    Female
2      Male
3      Male
4    Female
5    Female
6    Female
dtype: object

In [ ]:
import numpy as np

In [ ]:
pd.Series(np.array(['Male','Female','Male','Male','Female','Female','Female']))

0      Male
1    Female
2      Male
3      Male
4    Female
5    Female
6    Female
dtype: object

In [ ]:
ser = pd.Series(np.array(['Male','Female','Male','Male','Female','Female']))

In [ ]:
print(type(ser))

<class 'pandas.core.series.Series'>


Creating a Series with Dictionary

In [ ]:
dict_data = {'a':1,'b':2,'c':3}
dict_data

{'a': 1, 'b': 2, 'c': 3}

In [ ]:
pd.Series(dict_data)

a    1
b    2
c    3
dtype: int64

In [ ]:
ser1 = pd.Series(dict_data)
print(type(ser1))

<class 'pandas.core.series.Series'>


In [ ]:
ser1.index

Index(['a', 'b', 'c'], dtype='object')

In [ ]:
ser1.values

array([1, 2, 3])

Creating a Series with List

In [ ]:
list_data = ['2019-01-02',3.14,'ABC',100,True]

In [ ]:
ser2 = pd.Series(list_data)
ser2

0    2019-01-02
1          3.14
2           ABC
3           100
4          True
dtype: object

In [ ]:
ser2.index

RangeIndex(start=0, stop=5, step=1)

In [ ]:
ser2.values

array(['2019-01-02', 3.14, 'ABC', 100, True], dtype=object)

In [ ]:
pd.DataFrame({"Name":["Braund, Mr. Owen Harris",
                      "Allen, Mr. William Henry",
                      "Bonnell, Miss. Elizabeth"],
              "Age":[22,35,58],
              "Sex":["male","male","female"]})

Name  Age     Sex
0   Braund, Mr. Owen Harris   22    male
1  Allen, Mr. William Henry   35    male
2  Bonnell, Miss. Elizabeth   58  female

In [ ]:
df = pd.DataFrame({"Name" : ["Harhsa","Bhavana","Sanjana"],
                   "Age" : [22,35,58],
                   "Sex" : ["male","male","female"]})

In [ ]:
df['Age']

0    22
1    35
2    58
Name: Age, dtype: int64

In [ ]:
print(type(df['Age']))

<class 'pandas.core.series.Series'>


In [ ]:
df['Age'][0]

np.int64(22)

In [ ]:
df = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]])
df

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [ ]:
df.columns

RangeIndex(start=0, stop=3, step=1)

In [ ]:
df[0]

0    1
1    4
2    7
Name: 0, dtype: int64

In [ ]:
print(type(df[0]))

<class 'pandas.core.series.Series'>


In [ ]:
eye = pd.Series(['Brown','Blue','Hazel','Green'])
eye

0    Brown
1     Blue
2    Hazel
3    Green
dtype: object

In [ ]:
dict1 = {"Brown":220, "Blue":215, "Hazel":93, "Green":64}
dict1

{'Brown': 220, 'Blue': 215, 'Hazel': 93, 'Green': 64}

In [ ]:
eye = pd.Series(dict1)
eye

Brown    220
Blue     215
Hazel     93
Green     64
dtype: int64

In [ ]:
eye.index

Index(['Brown', 'Blue', 'Hazel', 'Green'], dtype='object')

In [ ]:
print(type(eye))

<class 'pandas.core.series.Series'>


In [ ]:
eye.name

In [ ]:
eye.name = "eye_color"
eye

Brown    220
Blue     215
Hazel     93
Green     64
Name: eye_color, dtype: int64

In [ ]:
eye.name

'eye_color'

In [ ]:
eye.index

Index(['Brown', 'Blue', 'Hazel', 'Green'], dtype='object')

In [ ]:
eye.values

array([220, 215,  93,  64])

In [ ]:
eye.sort_values()

Green     64
Hazel     93
Blue     215
Brown    220
Name: eye_color, dtype: int64

In [ ]:
eye.sort_index()

Blue     215
Brown    220
Green     64
Hazel     93
Name: eye_color, dtype: int64

In [ ]:
eye.unique()

array([220, 215,  93,  64])

In [ ]:
eye.nunique()

4

In [ ]:
my_data2 = [220,215,93,64,64]

In [ ]:
index2 = ['Brown','Blue','Blue','Hazel','Green']

In [ ]:
eye2 = pd.Series(data = my_data2, index = index2)
eye2

Brown    220
Blue     215
Blue      93
Hazel     64
Green     64
dtype: int64

In [ ]:
eye2.unique()

array([220, 215,  93,  64])

In [ ]:
eye2.nunique()

4

In [ ]:
eye2.value_counts()

64     2
220    1
215    1
93     1
Name: count, dtype: int64

In [ ]:
ser = pd.Series([0,10,20,30,40], index = ['a','b','c','d','e'])

In [ ]:
ser.iloc[1]

np.int64(10)

In [ ]:
ser['b']

np.int64(10)

In [ ]:
ser[1:3]

b    10
c    20
dtype: int64